### PR TITLE
Create typescript definition

### PR DESCRIPTION
**Pull request by guillaume-ro-fr**

### CODE REVIEW

**Comment by nmonterroso** [comment]
@guillaume-ro-fr thanks for contributing! Definitely appreciate having a TypeScript definition file. However, the `index.d.ts` file is not added to the `dist/` directory during `build`, so it wouldn't get published along with the rest of the module. 

I can do that if you'd like, but first please resolve the conflict in `package.json`.

**Comment by guillaume-ro-fr** [comment]
@nmonterroso Conflicts resolved, you can add the `index.d.ts` file in the `build` directory. Thanks !

**Comment by nmonterroso** [comment]
@guillaume-ro-fr I've published this as `v1.0.3`. Thanks again!

I'm not too familiar with TypeScript but this definition did catch my eye:
```ts
export class BlotSpec {
    ...
    getActions(): Action[];
    ...
}
```

In Flow this is defined as:
```js
getActions(): Class<Action>[]
```

So it's returning the class definition (not an instance of the class). Does the current definition work as expected?

**Comment by guillaume-ro-fr** [comment]
@nmonterroso I think you're right. I don't know enough things on Flow but according to this [doc](https://flow.org/en/docs/types/utilities/#toc-class), I think the simplest solution in Typescript is :
```typescript
export class BlotSpec {
     ...
    getActions(): (typeof Action)[];
    ...
}
```

I don't know another way to do that, and indeed this is a problem to instantiate a generic class, [for example](http://blakeembrey.com/articles/2015/04/typescript-constructor-of-type/)

**Comment by guillaume-ro-fr** [comment]
My correction : https://github.com/guillaume-ro-fr/quill-blot-formatter/commit/e52b1ea95a48721f0fcda1a585052c50b60c9685

I can make a pull request if you're ok

**Comment by nmonterroso** [comment]
👍 
I think if you can create a sample spec with it as a test and `getActions()` is able to return the [defaults](https://github.com/Fandom-OSS/quill-blot-formatter/blob/master/src/specs/BlotSpec.js#L18) without any compilation errors then it should be good to go.

**Comment by nmonterroso** [comment]
@guillaume-ro-fr any update on whether or not the fix works as you'd expect?

**Pull request merged**
